---
apiVersion: batch/v1
kind: Job
metadata:
  name: stunner-post-install
  labels: 
    job: stunner-job
spec:
  template:
    spec:
      serviceAccountName: job-sa
      containers:
      - name: post-install
        image: l7mp/stunner-job:latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash"]
        args: ["./job.sh"]
      restartPolicy: Never
  backoffLimit: 4
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: default
  name: svc-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["services"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""] 
  resources: ["configmaps"]
  verbs: ["get", "watch", "list", "patch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-sa
  namespace: default
  labels:
    job: stunner-job
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    crb: stunner-job
  name: prometheus-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: svc-reader
subjects:
- kind: ServiceAccount
  name: job-sa
  namespace: default
