version: v2
admin:
  name: stunnerd
  loglevel: $STUNNER_LOGLEVEL
  metrics_endpoint: "http://0.0.0.0:8080/metrics"
auth:
  type: $STUNNER_AUTH_TYPE
  realm: $STUNNER_REALM
  credentials:
    username: $STUNNER_USERNAME
    password: $STUNNER_PASSWORD
    secret: $STUNNER_SHARED_SECRET
listeners:
  - name: stunnerd-udp
    public_address: "$STUNNER_ADDR"
    protocol: UDP
    port: $STUNNER_PORT
    servers: [stunnerd]
  - name: stunnerd-tcp
    public_address: "$STUNNER_ADDR"
    protocol: TCP
    port: $STUNNER_PORT
    servers: [stunnerd]
  # - name: stunnerd-tls
  #   protocol: TLS
  #   port: 3479
  #   cert: <base64 PEM cert>
  #   key: <base64 PEM key>
  #   servers: [stunnerd]
servers:
  - name: stunnerd
    type: turn
    clusters:
      - open-udp
      - open-tcp
      # - media-servers
clusters:
  - name: open-udp
    protocol: UDP
    endpoints:
      - "0.0.0.0/0"
      - "::/0"
    addresses: ["$STUNNER_ADDR"]
  - name: open-tcp
    protocol: TCP
    endpoints:
      - "0.0.0.0/0"
      - "::/0"
    addresses: ["$STUNNER_ADDR"]
  # - name: media-servers
  #   type: STRICT_DNS
  #   protocol: UDP
  #   endpoints:
  #     - media-server.default.svc.cluster.local
  #   addresses: ["$STUNNER_ADDR"]
