site_name: STUNner
repo_url: https://github.com/l7mp/stunner
repo_name: STUNner
site_description: "Documentation of STUNner"
site_author: L7mp Technologies Kft.
copyright: L7mp Technologies Kft.
use_directory_urls: true
theme:
  name: readthedocs
  highlightjs: true
nav:
- 'Why STUNner': 'WHY.md'
- 'Deployment models': 'DEPLOYMENT.md'
- 'Concepts': 'CONCEPTS.md'
- 'Installation': 'INSTALL.md'
- 'Gateway API reference': 'GATEWAY.md'
- 'Security': 'SECURITY.md'
- 'Authentication': 'AUTH.md'
- 'Scaling': 'SCALING.md'
- 'Monitoring': 'MONITORING.md'
- 'Examples':
  - 'Configuring TLS for examples': 'examples/TLS.md'
  - 'Simple tunnel': 'examples/simple-tunnel/README.md'
  - 'Direct one to one call': 'examples/direct-one2one-call/README.md'
  - 'LiveKit': 'examples/livekit/README.md'
  - 'Janus': 'examples/janus/README.md'
  - 'Jitsi': 'examples/jitsi/README.md'
  - 'mediasoup': 'examples/mediasoup/README.md'
  - 'CloudRetro': 'examples/cloudretro/README.md'
  - 'N.eko': 'examples/neko/README.md'
  - 'Kurento one to one call': 'examples/kurento-one2one-call/README.md'
  - 'Kurento Magic Mirror': 'examples/kurento-magic-mirror/README.md'
  - 'Benchmark': 'examples/benchmark/README.md'
- 'CMD':
  - 'stunnerctl': 'cmd/stunnerctl.md'
  - 'stunnerd': 'cmd/stunnerd.md'
  - 'turncat': 'cmd/turncat.md'
plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
