#!/bin/bash

USAGE="stunnercli get-config <namespace/name>"

[ -z "$1" -o -z "$2" ] && echo $USAGE && exit 0
COMMAND="$1"
ARG="$2"

jq=$(which jq)
if [ -z "$jq" ] ; then
    echo "Error: cannot find jq in PATH" && exit 0
fi
jq="$jq -r"

# dumps only the first listener
get_config () {
    args=(${ARG//\// })
    namespace=${args[0]}
    name=${args[1]}
    [ -z $namespace -o -z $name ] && echo "cannot parse <namespace/name> argument" && exit 0

    tmpfile=$(mktemp "./stunnerd-config.XXXXXX")
    kubectl get cm -n $namespace $name -o jsonpath="{.data.stunnerd\.conf}" > $tmpfile
   
    local AUTH_TYPE=$($jq ".auth.type" $tmpfile)
    local USERNAME=$($jq ".auth.credentials.username" $tmpfile)
    local PASSWORD=$($jq ".auth.credentials.password" $tmpfile)
    local SECRET=$($jq ".auth.credentials.secret" $tmpfile)

    [ -n "$AUTH_TYPE" -a "$AUTH_TYPE" != "null" ] && echo -e "STUN/TURN authentication type:\t$AUTH_TYPE"
    [ -n "$USERNAME" -a "$USERNAME" != "null" ]   && echo -e "STUN/TURN username:\t\t$USERNAME"
    [ -n "$PASSWORD" -a "$PASSWORD" != "null" ]   && echo -e "STUN/TURN password:\t\t$PASSWORD"
    [ -n "$SECRET" -a "$SECRET" != "null" ]       && echo -e "STUN/TURN secret:\t\t$SECRET"
    
    local n=0
    for NAME in $($jq '.listeners[] | .name' $tmpfile); do
        local PROTOCOL=$($jq ".listeners[${n}].protocol" $tmpfile)
        local PUBLIC_ADDR=$($jq ".listeners[${n}].public_address" $tmpfile)
        local PUBLIC_PORT=$($jq ".listeners[${n}].public_port" $tmpfile)

        n=$((n+1))

        echo -e "Listener ${n}"
        [ -n "$NAME" -a "$NAME" != "null" ]               && echo -e "\tName:\t$NAME"
        [ -n "$NAME" -a "$NAME" != "null" ]               && echo -e "\tListener:\t$NAME"
        [ -n "$PROTOCOL" -a "$PROTOCOL" != "null" ]       && echo -e "\tProtocol:\t$PROTOCOL"
        [ -n "$PUBLIC_ADDR" -a "$PUBLIC_ADDR" != "null" ] && echo -e "\tPublic address:\t$PUBLIC_ADDR"
        [ -n "$PUBLIC_PORT" -a "$PUBLIC_PORT" != "null" ] && echo -e "\tPublic port:\t$PUBLIC_PORT"
    done
        
    rm -f $tmpfile
}

case $COMMAND in
    "get-config")
        get_config
        ;;

    *)
        echo "Unknown command: '$COMMAND'"
        exit 0
        ;;
esac

exit 1
