version: v1alpha1
admin:
  name: stunnerd
auth:
  type: static
  credentials:
    username: "user"
    password: "pass"
clusters:
  - name: open-cluster
    endpoints:
      - "0.0.0.0/0"
listeners:
  - name: udp-5000
    address: "127.0.0.1"
    protocol: udp
    port: 5000
    routes:
      - open-cluster
  - name: udp-6000
    address: "127.0.0.1"
    protocol: udp
    port: 6000
    routes:
      - open-cluster
  - name: udp-7000
    address: "127.0.0.1"
    protocol: udp
    port: 7000
    routes:
      - open-cluster
  - name: udp-8000
    address: "127.0.0.1"
    protocol: udp
    port: 8000
    routes:
      - open-cluster
