---
apiVersion: stunner.l7mp.io/v1
kind: Dataplane
metadata:
  name: default
spec:
  replicas: 1
  image: l7mp/stunnerd:latest
  imagePullPolicy: IfNotPresent
  command:
    - stunnerd
  args:
    - -w
    - --udp-thread-num=16
  resources:
    limits:
      cpu: 2
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 128Mi
  terminationGracePeriodSeconds: 3600
  hostNetwork: false
