name: "publish: Push Helm charts to web"

on:
  workflow_call:
    inputs:
      dev:
        description: Whether to release a dev version
        required: true
        type: boolean

jobs:
  push_charts:
    name: Push Helm charts to web
    runs-on: ubuntu-latest
    steps:
      - name: Get version for non-dev release
        if: ${{ inputs.dev == false || inputs.dev == 'false' }}
        id: vars
        run: echo tag=$(echo ${GITHUB_REF:11}) >> $GITHUB_OUTPUT

      - name: Trigger release workflow in the stunner-helm repo
        if: ${{ inputs.dev == false || inputs.dev == 'false' }}
        uses: benc-uk/workflow-dispatch@v1
        with:
          token: ${{ secrets.WEB_PAT_TOKEN }}
          repo: l7mp/stunner-helm
          workflow: publish.yaml
          inputs: '{"tag": "${{ steps.vars.outputs.tag }}", "type": "stunner"}'

      - name: Trigger release workflow in the stunner-helm repo
        if: ${{ inputs.dev == true || inputs.dev == 'true' }}
        uses: benc-uk/workflow-dispatch@v1
        with:
          token: ${{ secrets.WEB_PAT_TOKEN }}
          repo: l7mp/stunner-helm
          workflow: publish.yaml
          inputs: '{"tag": "dev", "type": "stunner"}'
