name: "publish: Add binaries to release assets"

on:
  workflow_call:

jobs:
  add_binaries:
    name: Add binaries to release assets
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: linux
            arch: amd64
            file_end: ""
          - os: linux
            arch: arm64
            file_end: ""

          - os: darwin
            arch: amd64
            file_end: ""
          - os: darwin
            arch: arm64
            file_end: ""

          - os: windows
            arch: amd64
            file_end: ".exe"
          - os: windows
            arch: arm64
            file_end: ".exe"

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10

      - name: Get version
        id: vars
        run: echo tag=$(echo ${GITHUB_REF:11}) >> $GITHUB_OUTPUT

      - name: Install Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c
        with:
          go-version: '1.26'

      - name: Build binaries
        run: |
          export CGO_ENABLED=0 GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }}
          make build-bin
          mv bin/turncat turncat-v${{ steps.vars.outputs.tag }}-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.file_end }}
          mv bin/stunnerctl stunnerctl-v${{ steps.vars.outputs.tag }}-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.file_end }}

      - name: Release turncat binary
        uses: svenstaro/upload-release-action@29e53e917877a24fad85510ded594ab3c9ca12de
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: turncat-v${{ steps.vars.outputs.tag }}-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.file_end }}
          tag: ${{ github.ref_name }}
          asset_name: turncat-v${{ steps.vars.outputs.tag }}-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.file_end }}

      - name: Release stunnerctl binary
        uses: svenstaro/upload-release-action@29e53e917877a24fad85510ded594ab3c9ca12de
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: stunnerctl-v${{ steps.vars.outputs.tag }}-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.file_end }}
          tag: ${{ github.ref_name }}
          asset_name: stunnerctl-v${{ steps.vars.outputs.tag }}-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.file_end }}
